# Generated by Django 5.2.8 on 2025-12-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_alter_track_uploader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='uploader',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='track',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='track',
            name='embedding',
        ),
        migrations.RemoveField(
            model_name='track',
            name='file',
        ),
        migrations.RemoveField(
            model_name='track',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='track',
            name='status',
        ),
        migrations.AddField(
            model_name='track',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='track',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='source_type',
            field=models.CharField(choices=[('upload', 'Uploaded File'), ('link', 'External Link')], default='upload', max_length=10),
        ),
        migrations.AddField(
            model_name='track',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
