# Generated by Django 5.2.8 on 2025-12-02 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_track_analysis_track_status_alter_track_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='master_file',
            field=models.FileField(blank=True, null=True, upload_to='masters/'),
        ),
    ]
