# Generated by Django 5.2.9 on 2025-12-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_track_master_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='lyrics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
