# Generated by Django 5.2.9 on 2025-12-19 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_track_lyrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='track',
            name='link',
        ),
        migrations.RemoveField(
            model_name='track',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='track',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='track',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='track',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('analyzed', 'Analyzed'), ('error', 'Error')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='TrackAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waveform', models.JSONField(blank=True, null=True)),
                ('rms', models.JSONField(blank=True, null=True)),
                ('spectral_centroid', models.JSONField(blank=True, null=True)),
                ('lyrics_raw', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='generator.track')),
            ],
        ),
    ]
