# Generated by Django 5.2.9 on 2025-12-19 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0007_remove_track_analysis_remove_track_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackanalysis',
            name='score',
        ),
        migrations.AddField(
            model_name='trackanalysis',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackanalysis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trackanalysis',
            name='vocal_pitch',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackanalysis',
            name='vocal_stats',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackanalysis',
            name='track',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_obj', to='generator.track'),
        ),
    ]
