# Generated by Django 5.2.9 on 2025-12-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0008_remove_trackanalysis_score_trackanalysis_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='source_type',
            field=models.CharField(default='upload', max_length=20),
        ),
    ]
