# Generated by Django 5.2.9 on 2025-12-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0009_track_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackanalysis',
            name='ai_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
