# Generated by Django 5.1.15 on 2026-01-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0010_trackanalysis_ai_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
