# Generated by Django 5.1.15 on 2026-02-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0012_stem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stem',
            name='created',
        ),
        migrations.AlterField(
            model_name='stem',
            name='file',
            field=models.FileField(upload_to='stems/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='stem',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
