# Generated by Django 5.2.9 on 2025-12-11 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tracks',
            field=models.FileField(blank=True, null=True, upload_to='tracks/'),
        ),
    ]
