# Generated by Django 5.2.9 on 2025-12-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_subscription_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
