# Generated by Django 5.1.15 on 2026-02-11 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0013_remove_stem_created_alter_stem_file_alter_stem_name'),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='challenged_track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battles_received', to='generator.track'),
        ),
        migrations.AddField(
            model_name='battle',
            name='duration_hours',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='battle',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
